---
- name: Submit resolved JCL to z/OS
  hosts: zoslab
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  vars:
    job_owner: IBMUSER
    vsam_name: IBMUSER.TEST02.KSDS

  tasks:

    - name: Delete KSDS if exists
      zos_data_set:
        name: "{{ vsam_name }}"
        state: absent

    - name: Create KSDS
      zos_data_set:
        name: "{{ vsam_name }}"
        type: ksds
        state: present
        record_length: 80
        key_length: 4
        key_offset: 0

    - name: Check KSDS records
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/templates/KSDS_records.txt"
      delegate_to: localhost
      register: ksds_file

    - name: Show KSDS records file
      ansible.builtin.debug:
        var: ksds_file

    - name: Load KSDS records
      zos_mvs_raw:
        pgm: idcams
        auth: true
        dds:
          - dd_data_set:
              dd_name: INPUT
              data_set_name: "{{ vsam_name }}"
          - dd_data_set:
              dd_name: OUTPUT
              data_set_name: "{{ vsam_name }}"
          - dd_input:
              dd_name: sysin
              content: |
                " REPRO -
                  INFILE(0001TEST RECORD 1) - 
                  OUTFILE(0002TEST RECORD 2)"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text

    - name: Fetch KSDS records
      zos_fetch:
        src: "{{ vsam_name }}"
        dest: "{{ playbook_dir }}/templates/KSDS_records.txt"
        flat: true