- name: Submit resolved JCL to z/OS
  hosts: zoslab
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  vars:
    job_owner: IBMUSER
    vsam_name: IBMUSER.TEST02.KSDS

  tasks:

    - name: DEFKSDS
      exec:
        pgm: IDCAMS
      dd:
    - name: SYSPRINT
      sysout: "*"
    - name: SYSOUT
      sysout: "*"
    - name: INDD
      inline: |
        0001TEST RECORD 1
        0002TEST RECORD 2
    - name: SYSIN
      symbols: JCLONLY
      inline: |
        DELETE &HLQ..TEST.KSDS
        IF LASTCC < 9 THEN -
          DEFINE CLUSTER( -
            NAME(&HLQ..TEST.KSDS) -
            RECORDSIZE(80 80) -
            CYLINDERS(2 1) -
            CISZ(4096) -
            INDEXED -
            KEYS(4 0) -
          ) -
          DATA( -
            NAME(&HLQ..TEST.KSDS.DATA) -
          ) -
          INDEX( -
            NAME(&HLQ..TEST.KSDS.INDEX) -
          )
          IF LASTCC = 0 THEN -
            REPRO INFILE(INDD) OUTDATASET(&HLQ..TEST.KSDS)
          IF LASTCC = 0 THEN -
            PRINT INDATASET(&HLQ..TEST.KSDS) CHAR