- name: TSO list members in a dataset
  hosts: zoslab
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core
  
  tasks:
    - name: Execute TSO command List Dataset(DSLIST)
      zos_tso_command:
       commands:
         - DSLIST DATASET('SYS1.PARMLIB')
      max_rc: 4