---
- name: Submit JCL member to z/OS
  hosts: zoslab
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    job_owner: IBMUSER
    hlq: IBMUSER
    mlq: GAMA01.LAB
    libname: JCL 
    primary_allocation: 2
    secondary_allocation: 4 
    jcl_dataset_name: "{{ job_owner }}.GAMA01.LAB.JCL"

  tasks:
    - name: Submit JCL in a PDSE member.
      ibm.ibm_zos_core.zos_job_submit:
        src: "{{ job_owner }}.GAMA01.LAB.JCL(HELLO)"
      register: job_result
    
    - name: Show job id
      ansible.builtin.debug:
        msg: "{{ job_result.jobs[0].job_id }}"

    - name: Show spool output
      debug:
        msg: "{{ job_output.jobs[0].ddnames | map(attribute='content') | list }}"